# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/gtelwifi/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/gtelwifi/proprietary/bin/calibration_init:system/bin/calibration_init \
    vendor/samsung/gtelwifi/proprietary/bin/ext_data.sh:system/bin/ext_data.sh \
    vendor/samsung/gtelwifi/proprietary/bin/ext_kill.sh:system/bin/ext_kill.sh \
    vendor/samsung/gtelwifi/proprietary/bin/ext_symlink.sh:system/bin/ext_symlink.sh \
    vendor/samsung/gtelwifi/proprietary/bin/inputfreq.sh:system/bin/inputfreq.sh \
    vendor/samsung/gtelwifi/proprietary/bin/modemd:system/bin/modemd \
    vendor/samsung/gtelwifi/proprietary/bin/nvitemd:system/bin/nvitemd \
    vendor/samsung/gtelwifi/proprietary/bin/phoneserver:system/bin/phoneserver \
    vendor/samsung/gtelwifi/proprietary/bin/prepare_param.sh:system/bin/prepare_param.sh \
    vendor/samsung/gtelwifi/proprietary/bin/refnotify:system/bin/refnotify \
    vendor/samsung/gtelwifi/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/gtelwifi/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
    vendor/samsung/gtelwifi/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/gtelwifi/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/gtelwifi/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/gtelwifi/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/gtelwifi/proprietary/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
    vendor/samsung/gtelwifi/proprietary/lib/drm/libomaplugin.so:system/lib/drm/libomaplugin.so \
    vendor/samsung/gtelwifi/proprietary/lib/egl/libGLES_mali.so:system/lib/egl/libGLES_mali.so \
    vendor/samsung/gtelwifi/proprietary/lib/hw/camera.sc8830.so:system/lib/hw/camera.sc8830.so \
    vendor/samsung/gtelwifi/proprietary/lib/hw/sensors.sc8830.so:system/lib/hw/sensors.sc8830.so \
    vendor/samsung/gtelwifi/proprietary/lib/libisp.so:system/lib/libisp.so \
    vendor/samsung/gtelwifi/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
    vendor/samsung/gtelwifi/proprietary/lib/libomx_aacdec_sprd.so:system/lib/libomx_aacdec_sprd.so \
    vendor/samsung/gtelwifi/proprietary/lib/libomx_apedec_sprd.so:system/lib/libomx_apedec_sprd.so \
    vendor/samsung/gtelwifi/proprietary/lib/libomx_avcdec_hw_sprd.so:system/lib/libomx_avcdec_hw_sprd.so \
    vendor/samsung/gtelwifi/proprietary/lib/libomx_avcdec_sw_sprd.so:system/lib/libomx_avcdec_sw_sprd.so \
    vendor/samsung/gtelwifi/proprietary/lib/libomx_avcenc_hw_sprd.so:system/lib/libomx_avcenc_hw_sprd.so \
    vendor/samsung/gtelwifi/proprietary/lib/libomx_m4vh263dec_hw_sprd.so:system/lib/libomx_m4vh263dec_hw_sprd.so \
    vendor/samsung/gtelwifi/proprietary/lib/libomx_m4vh263dec_sw_sprd.so:system/lib/libomx_m4vh263dec_sw_sprd.so \
    vendor/samsung/gtelwifi/proprietary/lib/libomx_m4vh263enc_hw_sprd.so:system/lib/libomx_m4vh263enc_hw_sprd.so \
    vendor/samsung/gtelwifi/proprietary/lib/libomx_mp3dec_sprd.so:system/lib/libomx_mp3dec_sprd.so \
    vendor/samsung/gtelwifi/proprietary/lib/libomx_vpxdec_hw_sprd.so:system/lib/libomx_vpxdec_hw_sprd.so \
    vendor/samsung/gtelwifi/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/gtelwifi/proprietary/lib/libreference-ril_sp.so:system/lib/libreference-ril_sp.so \
    vendor/samsung/gtelwifi/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/gtelwifi/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/gtelwifi/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/gtelwifi/proprietary/lib/libuvdenoise.so:system/lib/libuvdenoise.so \
    vendor/samsung/gtelwifi/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/gtelwifi/proprietary/vendor/firmware/BCM43430A1_001.002.009.0022.0000_Samsung_TabE_SM-T561_TEST_ONLY.hcd:system/vendor/firmware/BCM43430A1_001.002.009.0022.0000_Samsung_TabE_SM-T561_TEST_ONLY.hcd \
    vendor/samsung/gtelwifi/proprietary/vendor/firmware/vbc_eq:system/vendor/firmware/vbc_eq \
    vendor/samsung/gtelwifi/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/gtelwifi/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/samsung/gtelwifi/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so

PRODUCT_PACKAGES += \
    libatchannel
